language: node_js
sudo: false
node_js:
  - "9"
before_install:
  - yarn build
  - cd dist
script:
  - yarn test
deploy:
  skip_cleanup: true
  provider: npm
  email: "renehr9102@gmail.com"
  api_key: $API_TOKEN
  on:
    branch: master
