# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- azure-pipelines


resources:
  - repo: self

variables:
  vmImageName: 'ubuntu-latest'
  testImageName: bitknown_test

stages:
  - stage: Test
    displayName: 'Run gscan'
    jobs:
    - job: Test
      pool:
        vmImage: $(vmImageName)

      steps:
      - script: |
          docker build -f ./Dockerfile.test -t $(testImageName) .
          docker run --rm $(testImageName) yarn test

