# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- azure-pipelines


resources:
  - repo: self

variables:
  vmImageName: 'ubuntu-latest'

stages:
  - stage: Test
    displayName: 'Run gscan'
    jobs:
    - job: Test
      pool:
        vmImage: $(vmImageName)

      steps:
      - task: Docker@2
        displayName: 'Run gscan tests in container'
        inputs:
          command: build
          Dockerfile: ./Dockerfile.test
          tags: |
            bitknown_test
      - script: docker run --rm bitknown_test yarn test

          
